export const events = [
  {
    image: '/images/event1.png',
    title: 'Summer Startup Bootcamp',
    slug: 'summer-startup-bootcamp-2025',
    location: 'New York, NY',
    date: 'July 8-12, 2025',
    time: '9:00 AM - 5:00 PM',
  },
  {
    image: '/images/event2.png',
    title: 'Practical AI Workshop',
    slug: 'practical-ai-workshop-2025',
    location: 'San Francisco, CA',
    date: 'August 2, 2025',
    time: '1:00 PM - 4:00 PM',
  },
  {
    image: '/images/event3.png',
    title: 'City Music Festival',
    slug: 'city-music-festival-2025',
    location: 'Chicago, IL',
    date: 'September 10-12, 2025',
    time: '12:00 PM - 11:00 PM',
  },
  {
    image: '/images/event4.png',
    title: 'Autumn Design Fair',
    slug: 'autumn-design-fair-2025',
    location: 'Portland, OR',
    date: 'October 4, 2025',
    time: '10:00 AM - 6:00 PM',
  },
  {
    image: '/images/event5.png',
    title: 'Charity Run & Wellness Expo',
    slug: 'charity-run-wellness-2025',
    location: 'Boston, MA',
    date: 'November 1, 2025',
    time: '7:00 AM - 2:00 PM',
  },
  {
    image: '/images/event6.png',
    title: 'Winter Makers Market',
    slug: 'winter-makers-market-2025',
    location: 'Denver, CO',
    date: 'December 6, 2025',
    time: '11:00 AM - 7:00 PM',
  },
]
